name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # 在这里添加其他构建、测试、部署步骤

      # 创建并推送标签的步骤
      - name: Create and push tag
        if: github.ref == 'refs/heads/main' && github.event_name == 'push' # 仅在从 main 分支推送代码时执行
        env:
          GITHUB_TOKEN: ${{ secrets.DROID_TOKEN }}  # 添加个人访问令牌作为环境变量
        run: |
          # 获取最新的 Git 版本号
          echo "Hello, world!"
          export VERSION=$(git describe --abbrev=0 --tags)
          echo "$VERSION"
          # 将版本号加 1
          export NEW_VERSION=$(echo $VERSION | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
          echo "$NEW_VERSION"
          # 创建新标签并推送到远程仓库
          git tag $NEW_VERSION
          git push --tags origin main  # 使用个人访问令牌进行身份验证
